packages:
  # executable/launchable applications
  - 'apps/*'
  # all packages in subdirs of packages/ and components/
  - 'packages/*'
  # all packages in subdirs of packages/ and components/
  - 'backend/*'
